version: 2.1
orbs:
  node: circleci/node@1.0.0
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    executor: node/node

    steps:
      - checkout

      - run:
          name: Make fake certs
          command: |
            touch data/private_key.pem
            touch data/pub.key
            touch data/cert.pem

      - run: |
          npm ci

      - run:
          name: Run Tests
          command: npm run lint-test

      - codecov/upload:
          file: coverage/*.xml
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

      - store_artifacts:
          path: coverage
