[metadata]
name = 'update_server'
version = '0.0.1'
description = ''
author = 'Jo Becher'
author_email = 'jwbecher@gmail.com'
license = 'MIT/Apache-2.0'
url = 'https://github.com/_/update_server'

[requires]
python_version = ['2.7', '3.5', '3.6', 'pypy', 'pypy3']

[build-system]
requires = ['setuptools', 'wheel']

[tool.hatch.commands]
prerelease = 'hatch build'
